---
name : Scrape Word of the Day

on:
  schedule:
  - cron: "0 20 * * *" # Runs daily at minute: 0, hour: 20 UTC.  Every day, every month, every day of the week
  workflow_dispatch: # Allows manual triggering
jobs:
  scrape: #job name
    runs-on: ubuntu-latest #run the job on an ubuntu VM with latest OS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run the scraper
        run: python scrape_word.py

      - name: Commit and push changes
        run: |
          DATE=$(date +'%Y-%m-%d') # Capture the current date
          git config --global user.name "YourGitHubUsername"
          git config --global user.email "your-email@example.com"
          git add word_of_the_day.md
          git commit -m "Update word of the day for ${DATE}" || echo "No changes to commit"
          git push
---