name : Scrape Word of the Day

on:
  schedule:
  - cron: "0 20 * * *" # Runs daily at minute: 0, hour: 20 UTC.  Every day, every month, every day of the week
  workflow_dispatch: # Allows manual triggering
  
jobs:
  scrape: #job name
    runs-on: ubuntu-latest #run the job on an ubuntu VM with latest OS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        run: python scrape_word.py

      - name: Commit and push changes
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')  # Add a timestamp to make the message unique
          git config --global user.name "gacetta"
          git config --global user.email "michael.gacetta@gmail.com"
          git pull origin main --rebase
          git add word_of_the_day.md
          git commit -m "Update word of the day for ${TIMESTAMP}" || echo "No changes to commit"
          git push