name: Test Cron Scheduling

on:
  schedule:
    - cron: "* 20 * * *"  # Runs every 2 minutes for testing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run date command
        run: date  # Outputs the current date and time to verify the cron trigger
